
/*卡牌 type  1 红桃 2黑桃 3梅花 4方块*/
var Cards = function(){
    this.data = [
        {url: 'cards_json.king', type: 0, val: 17},
        {url: 'cards_json.queen', type: 0, val: 16},
        {url: 'cards_json.hearts_1', type: 1, val: 14},
        {url: 'cards_json.hearts_2', type: 1, val: 15},
        {url: 'cards_json.hearts_3', type: 1, val: 3},
        {url: 'cards_json.hearts_4', type: 1, val: 4},
        {url: 'cards_json.hearts_5', type: 1, val: 5},
        {url: 'cards_json.hearts_6', type: 1, val: 6},
        {url: 'cards_json.hearts_7', type: 1, val: 7},
        {url: 'cards_json.hearts_8', type: 1, val: 8},
        {url: 'cards_json.hearts_9', type: 1, val: 9},
        {url: 'cards_json.hearts_10', type: 1, val: 10},
        {url: 'cards_json.hearts_11', type: 1, val: 11},
        {url: 'cards_json.hearts_12', type: 1, val: 12},
        {url: 'cards_json.hearts_13', type: 1, val: 13},
        {url: 'cards_json.spades_1', type: 2, val: 14},
        {url: 'cards_json.spades_2', type: 2, val: 15},
        {url: 'cards_json.spades_3', type: 2, val: 3},
        {url: 'cards_json.spades_4', type: 2, val: 4},
        {url: 'cards_json.spades_5', type: 2, val: 5},
        {url: 'cards_json.spades_6', type: 2, val:6},
        {url: 'cards_json.spades_7', type: 2, val: 7},
        {url: 'cards_json.spades_8', type: 2, val: 8},
        {url: 'cards_json.spades_9', type: 2, val: 9},
        {url: 'cards_json.spades_10', type: 2, val: 10},
        {url: 'cards_json.spades_11', type: 2, val: 11},
        {url: 'cards_json.spades_12', type: 2, val: 12},
        {url: 'cards_json.spades_13', type: 2, val: 13},
        {url: 'cards_json.clubs_1', type: 3, val: 14},
        {url: 'cards_json.clubs_2', type: 3, val: 15},
        {url: 'cards_json.clubs_3', type: 3, val: 3},
        {url: 'cards_json.clubs_4', type: 3, val: 4},
        {url: 'cards_json.clubs_5', type: 3, val: 5},
        {url: 'cards_json.clubs_6', type: 3, val: 6},
        {url: 'cards_json.clubs_7', type: 3, val: 7},
        {url: 'cards_json.clubs_8', type: 3, val: 8},
        {url: 'cards_json.clubs_9', type: 3, val:9},
        {url: 'cards_json.clubs_10', type: 3, val: 10},
        {url: 'cards_json.clubs_11', type: 3, val: 11},
        {url: 'cards_json.clubs_12', type: 3, val: 12},
        {url: 'cards_json.clubs_13', type: 3, val: 13},
        {url: 'cards_json.diamonds_1', type: 4, val: 14},
        {url: 'cards_json.diamonds_2', type: 4, val: 15},
        {url: 'cards_json.diamonds_3', type: 4, val: 3},
        {url: 'cards_json.diamonds_4', type: 4, val: 4},
        {url: 'cards_json.diamonds_5', type: 4, val: 5},
        {url: 'cards_json.diamonds_6', type: 4, val: 6},
        {url: 'cards_json.diamonds_7', type: 4, val: 7},
        {url: 'cards_json.diamonds_8', type: 4, val: 8},
        {url: 'cards_json.diamonds_9', type: 4, val: 9},
        {url: 'cards_json.diamonds_10', type: 4, val: 10},
        {url: 'cards_json.diamonds_11', type: 4, val: 11},
        {url: 'cards_json.diamonds_12', type: 4, val: 12},
        {url: 'cards_json.diamonds_13', type: 4, val: 13}
    ];
    this.data1 =[
        {url: 'cards_json.hearts_1', type: 1, val: 50},
        {url: 'cards_json.hearts_2', type: 1, val: 2},
        {url: 'cards_json.hearts_3', type: 1, val: 6},
        {url: 'cards_json.hearts_4', type: 1, val: 10},
        {url: 'cards_json.hearts_5', type: 1, val: 14},
        {url: 'cards_json.hearts_6', type: 1, val: 18},
        {url: 'cards_json.hearts_7', type: 1, val: 22},
        {url: 'cards_json.hearts_8', type: 1, val: 26},
        {url: 'cards_json.hearts_9', type: 1, val: 30},
        {url: 'cards_json.hearts_10', type: 1, val: 34},
        {url: 'cards_json.hearts_11', type: 1, val: 38},
        {url: 'cards_json.hearts_12', type: 1, val: 42},
        {url: 'cards_json.hearts_13', type: 1, val: 46},
        {url: 'cards_json.spades_1', type: 2, val: 51},
        {url: 'cards_json.spades_2', type: 2, val: 3},
        {url: 'cards_json.spades_3', type: 2, val: 7},
        {url: 'cards_json.spades_4', type: 2, val: 11},
        {url: 'cards_json.spades_5', type: 2, val: 15},
        {url: 'cards_json.spades_6', type: 2, val:19},
        {url: 'cards_json.spades_7', type: 2, val: 23},
        {url: 'cards_json.spades_8', type: 2, val: 27},
        {url: 'cards_json.spades_9', type: 2, val: 31},
        {url: 'cards_json.spades_10', type: 2, val: 35},
        {url: 'cards_json.spades_11', type: 2, val: 39},
        {url: 'cards_json.spades_12', type: 2, val: 43},
        {url: 'cards_json.spades_13', type: 2, val: 47},
        {url: 'cards_json.clubs_1', type: 3, val: 49},
        {url: 'cards_json.clubs_2', type: 3, val: 1},
        {url: 'cards_json.clubs_3', type: 3, val: 5},
        {url: 'cards_json.clubs_4', type: 3, val: 9},
        {url: 'cards_json.clubs_5', type: 3, val: 13},
        {url: 'cards_json.clubs_6', type: 3, val: 17},
        {url: 'cards_json.clubs_7', type: 3, val: 21},
        {url: 'cards_json.clubs_8', type: 3, val: 25},
        {url: 'cards_json.clubs_9', type: 3, val:29},
        {url: 'cards_json.clubs_10', type: 3, val: 33},
        {url: 'cards_json.clubs_11', type: 3, val: 37},
        {url: 'cards_json.clubs_12', type: 3, val: 41},
        {url: 'cards_json.clubs_13', type: 3, val: 45},
        {url: 'cards_json.diamonds_1', type: 4, val: 48},
        {url: 'cards_json.diamonds_2', type: 4, val: 0},
        {url: 'cards_json.diamonds_3', type: 4, val: 4},
        {url: 'cards_json.diamonds_4', type: 4, val: 8},
        {url: 'cards_json.diamonds_5', type: 4, val: 12},
        {url: 'cards_json.diamonds_6', type: 4, val: 16},
        {url: 'cards_json.diamonds_7', type: 4, val: 20},
        {url: 'cards_json.diamonds_8', type: 4, val: 24},
        {url: 'cards_json.diamonds_9', type: 4, val: 28},
        {url: 'cards_json.diamonds_10', type: 4, val: 32},
        {url: 'cards_json.diamonds_11', type: 4, val: 36},
        {url: 'cards_json.diamonds_12', type: 4, val: 40},
        {url: 'cards_json.diamonds_13', type: 4, val: 44}        
    ]

}
Cards.prototype.getNewGards = function(){
    return this.data.slice(0);
}
module.exports = Cards;